import { LeagueSettings, Player, WaiverTarget } from "./types";

export const DEFAULT_LEAGUE: LeagueSettings = {
  managerName: "",
  teamName: "",
  platform: "ESPN",
  scoring: "PPR",
  currentWeek: 3,
  currentOpponent: "",
  waiverType: "Not sure yet",
  beginnerMode: true,
  onboardingComplete: false,
  openaiApiKey: "",
};

export function samplePlayers(): Player[] {
  return [
    {
      id: "sample-qb",
      name: "Caleb Williams",
      nflTeam: "CHI",
      position: "QB",
      opponent: "MIN",
      projectedPoints: 19.4,
      status: "Healthy",
      matchup: "Average",
      opportunity: "Averaging 34 pass attempts over last 3 games.",
      consistency: "Boom/Bust",
      slot: "QB",
      notes: "",
      isSample: true,
    },
    {
      id: "sample-rb1",
      name: "Breece Hall",
      nflTeam: "NYJ",
      position: "RB",
      opponent: "GB",
      projectedPoints: 15.8,
      status: "Healthy",
      matchup: "Average",
      opportunity: "18 touches last week, lead back role.",
      consistency: "Steady",
      slot: "RB1",
      notes: "",
      isSample: true,
    },
    {
      id: "sample-rb2",
      name: "Rico Dowdle",
      nflTeam: "PIT",
      position: "RB",
      opponent: "NE",
      projectedPoints: 10.1,
      status: "Questionable",
      matchup: "Tough",
      opportunity: "Limited in Friday practice with an ankle issue.",
      consistency: "Boom/Bust",
      slot: "RB2",
      notes: "Re-check Sunday morning.",
      isSample: true,
    },
    {
      id: "sample-wr1",
      name: "Puka Nacua",
      nflTeam: "LAR",
      position: "WR",
      opponent: "NYG",
      projectedPoints: 0,
      status: "Out",
      matchup: "Good",
      opportunity: "Ruled out with a hamstring injury.",
      consistency: "Steady",
      slot: "WR1",
      notes: "Needs a replacement before kickoff.",
      isSample: true,
    },
    {
      id: "sample-wr2",
      name: "Zay Flowers",
      nflTeam: "BAL",
      position: "WR",
      opponent: "NO",
      projectedPoints: 13.4,
      status: "Healthy",
      matchup: "Great",
      opportunity: "8+ targets in 2 of last 3 games.",
      consistency: "Steady",
      slot: "WR2",
      notes: "",
      isSample: true,
    },
    {
      id: "sample-te",
      name: "Trey McBride",
      nflTeam: "ARI",
      position: "TE",
      opponent: "SEA",
      projectedPoints: 14.5,
      status: "Healthy",
      matchup: "Average",
      opportunity: "Top-5 TE in targets this season.",
      consistency: "Steady",
      slot: "TE",
      notes: "",
      isSample: true,
    },
    {
      id: "sample-flex",
      name: "Jaylen Waddle",
      nflTeam: "MIA",
      position: "WR",
      opponent: "SF",
      projectedPoints: 12.2,
      status: "Healthy",
      matchup: "Tough",
      opportunity: "Target share dipped last 2 weeks.",
      consistency: "Boom/Bust",
      slot: "FLEX",
      notes: "",
      isSample: true,
    },
    {
      id: "sample-dst",
      name: "Buccaneers D/ST",
      nflTeam: "TB",
      position: "D/ST",
      opponent: "CLE",
      projectedPoints: 8.2,
      status: "Healthy",
      matchup: "Good",
      opportunity: "Facing a rookie QB this week.",
      consistency: "Unknown",
      slot: "DST",
      notes: "",
      isSample: true,
    },
    {
      id: "sample-k",
      name: "Brandon Aubrey",
      nflTeam: "DAL",
      position: "K",
      opponent: "PHI",
      projectedPoints: 9.6,
      status: "Healthy",
      matchup: "Average",
      opportunity: "Top scoring kicker this season.",
      consistency: "Steady",
      slot: "K",
      notes: "",
      isSample: true,
    },
    {
      id: "sample-bench1",
      name: "Jordan Mason",
      nflTeam: "MIN",
      position: "RB",
      opponent: "CHI",
      projectedPoints: 11.6,
      status: "Healthy",
      matchup: "Good",
      opportunity: "Emerging as a bigger part of the backfield.",
      consistency: "Steady",
      slot: "BENCH",
      notes: "Possible replacement for an OUT starter.",
      isSample: true,
    },
    {
      id: "sample-bench2",
      name: "Khalil Shakir",
      nflTeam: "BUF",
      position: "WR",
      opponent: "NYJ",
      projectedPoints: 10.9,
      status: "Healthy",
      matchup: "Good",
      opportunity: "Slot role growing with QB1 healthy.",
      consistency: "Steady",
      slot: "BENCH",
      notes: "",
      isSample: true,
    },
    {
      id: "sample-bench3",
      name: "Will Levis",
      nflTeam: "TEN",
      position: "QB",
      opponent: "IND",
      projectedPoints: 15.2,
      status: "Healthy",
      matchup: "Average",
      opportunity: "Backup QB depth.",
      consistency: "Unknown",
      slot: "BENCH",
      notes: "",
      isSample: true,
    },
    {
      id: "sample-bench4",
      name: "Michael Pittman Jr.",
      nflTeam: "IND",
      position: "WR",
      opponent: "TEN",
      projectedPoints: 0,
      status: "Bye",
      matchup: "Average",
      opportunity: "On a bye this week.",
      consistency: "Steady",
      slot: "BENCH",
      notes: "",
      isSample: true,
    },
  ];
}

export function sampleWaivers(): WaiverTarget[] {
  return [
    {
      id: "sample-w1",
      name: "Jaylen Warren",
      nflTeam: "PIT",
      position: "RB",
      projectedPoints: 12.8,
      trend: "Rising",
      notes: "Seeing more red-zone touches the last two weeks and your RB room needs healthy depth.",
      priority: "High",
      potentialDrop: "Bench WR you rarely start",
      isSample: true,
    },
    {
      id: "sample-w2",
      name: "Ricky Pearsall",
      nflTeam: "SF",
      position: "WR",
      projectedPoints: 10.9,
      trend: "Rising",
      notes: "Target share climbing as the offense opens up.",
      priority: "Medium",
      potentialDrop: "Your QB2 if you only need one",
      isSample: true,
    },
    {
      id: "sample-w3",
      name: "Seahawks D/ST",
      nflTeam: "SEA",
      position: "D/ST",
      projectedPoints: 9.1,
      trend: "Steady",
      notes: "Favorable matchup this week if your current defense has a tough opponent.",
      priority: "Low",
      potentialDrop: "Your current D/ST for one week only",
      isSample: true,
    },
  ];
}

export const DEMO_MANAGER_NAME = "Cesar";
export const DEMO_TEAM_NAME = "Cesar's Cool Team";
export const DEMO_OPPONENT = "Asha's Team";
